#!/bin/bash
# Trim 03-generics junior/middle from 120 to 50 puzzles each.
set -e
cd "$(dirname "$0")"

# junior: drop 70, keep 50
rm -rf junior/accgen
rm -rf junior/anyofgen
rm -rf junior/anyslicepitfall
rm -rf junior/appendifgen
rm -rf junior/betweengen
rm -rf junior/boundsgen
rm -rf junior/chaingen
rm -rf junior/clampslice
rm -rf junior/cmporgen
rm -rf junior/coalescegen
rm -rf junior/comparablepitfall
rm -rf junior/concatgen
rm -rf junior/constraintifcmethod
rm -rf junior/counterstruct
rm -rf junior/countgen
rm -rf junior/countpositive
rm -rf junior/dedupestdlib
rm -rf junior/defaultmapgen
rm -rf junior/dequegen
rm -rf junior/derefgen
rm -rf junior/equalslices
rm -rf junior/fillgen
rm -rf junior/flattengen
rm -rf junior/getordefault
rm -rf junior/groupsizegen
rm -rf junior/indexbygen
rm -rf junior/indexmax
rm -rf junior/iszerogen
rm -rf junior/keysgen
rm -rf junior/lengthof
rm -rf junior/mapmethodlesson
rm -rf junior/mapscopygen
rm -rf junior/mapsequalgen
rm -rf junior/maxbykey
rm -rf junior/minslice
rm -rf junior/multimapgen
rm -rf junior/mustgen
rm -rf junior/nilslicepitfall
rm -rf junior/nodegen
rm -rf junior/normalizegen
rm -rf junior/percentgen
rm -rf junior/productgen
rm -rf junior/ptrofgen
rm -rf junior/ptrslicehelper
rm -rf junior/rangegen
rm -rf junior/registrygen
rm -rf junior/repeatgen
rm -rf junior/resultgen
rm -rf junior/setopsgen
rm -rf junior/signgen
rm -rf junior/slicescontainsfunc
rm -rf junior/slicesdeletegen
rm -rf junior/slicesequalstd
rm -rf junior/slicesindexfunc
rm -rf junior/slicesinsertgen
rm -rf junior/slicesreversestd
rm -rf junior/slicessortbasic
rm -rf junior/slicetypegen
rm -rf junior/sortedkeysgen
rm -rf junior/sorteduniquegen
rm -rf junior/stackembed
rm -rf junior/stringerifc
rm -rf junior/sumvalues
rm -rf junior/swaptypegen
rm -rf junior/tofloats
rm -rf junior/tosetgen
rm -rf junior/trackergen
rm -rf junior/triplegen
rm -rf junior/valuesgen
rm -rf junior/zippairs

# middle: drop 70, keep 50
rm -rf middle/addviamethodgen
rm -rf middle/anyfallbackgen
rm -rf middle/asserteqgen
rm -rf middle/batchergen
rm -rf middle/boxingcostgen
rm -rf middle/bucketsgen
rm -rf middle/buildergen
rm -rf middle/bytestringgen
rm -rf middle/cartesiangen
rm -rf middle/chainmapgen
rm -rf middle/chunkbygen
rm -rf middle/clone2dgen
rm -rf middle/combineconstraint
rm -rf middle/comparablekeygen
rm -rf middle/countbygen
rm -rf middle/detmapgen
rm -rf middle/differencegen
rm -rf middle/dropwhilegen
rm -rf middle/eithergen
rm -rf middle/equalbygen
rm -rf middle/everynthgen
rm -rf middle/groupconsecutivegen
rm -rf middle/idvalidate
rm -rf middle/indexedlistgen
rm -rf middle/insertsortedgen
rm -rf middle/interleavegen
rm -rf middle/intersectgen
rm -rf middle/keystringgen
rm -rf middle/lastindexgen
rm -rf middle/lazygen
rm -rf middle/lazymapgen
rm -rf middle/mapdeepclonegen
rm -rf middle/measurablegen
rm -rf middle/minlessergen
rm -rf middle/modegen
rm -rf middle/multisetgen
rm -rf middle/mycmpgen
rm -rf middle/parseintorgen
rm -rf middle/pipelinegen
rm -rf middle/poolgen
rm -rf middle/positivegen
rm -rf middle/rangesumgen
rm -rf middle/receiverfuncgen
rm -rf middle/requirelengen
rm -rf middle/resultchaingen
rm -rf middle/ringidxgen
rm -rf middle/roundgen
rm -rf middle/scaleintgen
rm -rf middle/searchbygen
rm -rf middle/setmethodgen
rm -rf middle/slicesclipgen
rm -rf middle/slicescomparefunc
rm -rf middle/slicesequalfunc
rm -rf middle/slicesissortedfunc
rm -rf middle/slicesrepeatstd
rm -rf middle/sortbykeygen
rm -rf middle/sortlessergen
rm -rf middle/sortstablecheckgen
rm -rf middle/sparsegridgen
rm -rf middle/splitatgen
rm -rf middle/stackofstacksgen
rm -rf middle/statemachinegen
rm -rf middle/treemapgen
rm -rf middle/typesetmethodgen
rm -rf middle/unitclamp
rm -rf middle/unitmulgen
rm -rf middle/vecgen
rm -rf middle/versionedgen
rm -rf middle/whennotgenericgen
rm -rf middle/windowmaxgen

